### ISSUE TITLE
Error when running vulnix from builder

### ISSUE THREAD

**Issue by basvandijk** [flyingcircusio/vulnix#12]
I would like to integrate `vulnix` into our Hydra CI service. I have the following function which can be applied to a Nix store path resulting in a Hydra build product containing the vulnix report:

``` nix
vulnix = name : path : pkgs.stdenv.mkDerivation {
  name = "${name}-vulnix-report";
  buildInputs = [ pkgs.vulnix ];
  buildCommand = ''
    mkdir -p $out/nix-support
    vulnix ${path} > $out/vulnix-report
    echo "report vulnix $out/vulnix-report" > $out/nix-support/hydra-build-products
  '';
```

However running `vulnix` from within the builder produces the following error:

```
Traceback (most recent call last):
  File "/nix/store/nynmlv61b61k7z2jjsqxknpcz0m3dizh-python3.5-vulnix-v1.0/bin/.vulnix-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/xqamzf640vgy9qmiqfpw1affm390v0yg-python3.5-click-6.6/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/xqamzf640vgy9qmiqfpw1affm390v0yg-python3.5-click-6.6/lib/python3.5/site-packages/click/core.py", line 675, in main
    _verify_python3_env()
  File "/nix/store/xqamzf640vgy9qmiqfpw1affm390v0yg-python3.5-click-6.6/lib/python3.5/site-packages/click/_unicodefun.py", line 119, in _verify_python3_env
    'mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Either run this under Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.

Additional information: on this system no suitable UTF-8
locales were discovered.  This most likely requires resolving
by reconfiguring the locale system.
```

This looks similar to https://github.com/madjar/nox/issues/19.

Apparently the only locales active in a stdenv.mkDerivation builder are `C` and `POSIX`.

**Comment by basvandijk** [comment]
I solved it by setting the locale directly using:

```nix
vulnix = name : path : pkgs.stdenv.mkDerivation {
  name = "${name}-vulnix-report";
  buildInputs = [ pkgs.vulnix pkgs.glibcLocales ];
  buildCommand = ''
    export LC_ALL=en_US.utf8
    export LANG=en_US.utf8
    mkdir -p $out/nix-support
    vulnix ${path} > $out/vulnix-report
    echo "report vulnix $out/vulnix-report" > $out/nix-support/hydra-build-products
  '';
```

Now I'm getting an other error:

```

Traceback (most recent call last):
  File "/nix/store/nynmlv61b61k7z2jjsqxknpcz0m3dizh-python3.5-vulnix-v1.0/bin/.vulnix-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/xqamzf640vgy9qmiqfpw1affm390v0yg-python3.5-click-6.6/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/xqamzf640vgy9qmiqfpw1affm390v0yg-python3.5-click-6.6/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/nix/store/xqamzf640vgy9qmiqfpw1affm390v0yg-python3.5-click-6.6/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/xqamzf640vgy9qmiqfpw1affm390v0yg-python3.5-click-6.6/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/nynmlv61b61k7z2jjsqxknpcz0m3dizh-python3.5-vulnix-v1.0/lib/python3.5/site-packages/vulnix/main.py", line 156, in main
    store = populate_store(gc_roots, system, user, path)
  File "/nix/store/nynmlv61b61k7z2jjsqxknpcz0m3dizh-python3.5-vulnix-v1.0/lib/python3.5/site-packages/vulnix/main.py", line 111, in populate_store
    store.add_path(path)
  File "/nix/store/nynmlv61b61k7z2jjsqxknpcz0m3dizh-python3.5-vulnix-v1.0/lib/python3.5/site-packages/vulnix/nix.py", line 39, in add_path
    deriver = call(['nix-store', '-qd', path]).strip()
  File "/nix/store/nynmlv61b61k7z2jjsqxknpcz0m3dizh-python3.5-vulnix-v1.0/lib/python3.5/site-packages/vulnix/nix.py", line 13, in call
    output = subprocess.check_output(cmd, stderr=capture)
  File "/nix/store/7yk5vsdlf6jq96qqy20mhzpyw852ivbn-python3-3.5.1/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "/nix/store/7yk5vsdlf6jq96qqy20mhzpyw852ivbn-python3-3.5.1/lib/python3.5/subprocess.py", line 696, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/7yk5vsdlf6jq96qqy20mhzpyw852ivbn-python3-3.5.1/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/nix/store/7yk5vsdlf6jq96qqy20mhzpyw852ivbn-python3-3.5.1/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'nix-store'
```

Which is easily solved by adding `pkgs.nix` to the `buildInputs`. But after that I get the following:

```
error: Nix database directory ‘/nix/var/nix/db’ is not writable: Permission denied
```

**Comment by ckauhaus** [comment]
Thanks for the bug report. I'll have a look at it.

**Comment by ckauhaus** [comment]
I've documented some system requirements. `vulnix` uses common Nix tools (thus they must be in PATH) and these, in turn, require access to the store db. I recoment to set up `nix-daemon`.
