### ISSUE TITLE
Issue running vulnix 1.8.2

### ISSUE THREAD

**Issue by PsyanticY** [flyingcircusio/vulnix#56]
Hi, running vulnix on multiple derivation results in this error.

```$ vulnix -j /nix/store/r4xd3xpbn5mgp53fs7417yi9yhkdx3ad-nixos-system-monacol.grafana-19.09.git.108021d.drv
Traceback (most recent call last):
  File "/nix/store/ihhm7r0nwmhfx2v1qhd3q0cp6a3a52a6-vulnix-1.8.2/bin/.vulnix-wrapped", line 11, in <module>
    sys.exit(main())
  File "/nix/store/5xr7mcmiiqxcyd6c2540i8dyxvjrhxc0-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/5xr7mcmiiqxcyd6c2540i8dyxvjrhxc0-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/5xr7mcmiiqxcyd6c2540i8dyxvjrhxc0-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/5xr7mcmiiqxcyd6c2540i8dyxvjrhxc0-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/ihhm7r0nwmhfx2v1qhd3q0cp6a3a52a6-vulnix-1.8.2/lib/python3.7/site-packages/vulnix/main.py", line 138, in main
    nvd.update()
  File "/nix/store/ihhm7r0nwmhfx2v1qhd3q0cp6a3a52a6-vulnix-1.8.2/lib/python3.7/site-packages/vulnix/nvd.py", line 99, in update
    self.has_updates |= archive.update(self.mirror)
  File "/nix/store/ihhm7r0nwmhfx2v1qhd3q0cp6a3a52a6-vulnix-1.8.2/lib/python3.7/site-packages/vulnix/nvd.py", line 193, in update
    with Download(mirror + self.upstream_filename) as xml:
  File "/nix/store/ihhm7r0nwmhfx2v1qhd3q0cp6a3a52a6-vulnix-1.8.2/lib/python3.7/site-packages/vulnix/nvd.py", line 142, in __enter__
    self.xml = decompress(r.raw)
  File "/nix/store/ihhm7r0nwmhfx2v1qhd3q0cp6a3a52a6-vulnix-1.8.2/lib/python3.7/site-packages/vulnix/nvd.py", line 122, in decompress
    shutil.copyfileobj(f_in, tf)
  File "/nix/store/4c3z5r6yxsf2cxwwyazhdn92xixn4j5b-python3-3.7.5/lib/python3.7/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/nix/store/4c3z5r6yxsf2cxwwyazhdn92xixn4j5b-python3-3.7.5/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/nix/store/4c3z5r6yxsf2cxwwyazhdn92xixn4j5b-python3-3.7.5/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/nix/store/4c3z5r6yxsf2cxwwyazhdn92xixn4j5b-python3-3.7.5/lib/python3.7/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/nix/store/4c3z5r6yxsf2cxwwyazhdn92xixn4j5b-python3-3.7.5/lib/python3.7/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'<!')
```

vulnix: 
`$ vulnix --version
vulnix 1.8.2
`
nix:
`$ nix --version
nix (Nix) 2.3pre6631_e58a7144
`
i m sure I did run it before on the same server and it produced good results.

Any idea what this issue can be ?

**Comment by ckauhaus** [comment]
A fix is already in master. Expect a release soon.

**Comment by PsyanticY** [comment]
@ckauhaus Thanks a lot
