### ISSUE TITLE
Backport vulnix 1.9.x to 19.09

### ISSUE THREAD

**Issue by dR3b** [flyingcircusio/vulnix#59]
After a "nixos-rebuild switch" (19.09) I cannot start "vulnix":
```
vulnix --system

Traceback (most recent call last):
  File "/nix/store/4zyb0g5h6vfnxrzhl6h7v2bsja82s6yb-vulnix-1.8.2/bin/.vulnix-wrapped", line 11, in <module>
    sys.exit(main())
  File "/nix/store/5xr7mcmiiqxcyd6c2540i8dyxvjrhxc0-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/5xr7mcmiiqxcyd6c2540i8dyxvjrhxc0-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/5xr7mcmiiqxcyd6c2540i8dyxvjrhxc0-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/5xr7mcmiiqxcyd6c2540i8dyxvjrhxc0-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/4zyb0g5h6vfnxrzhl6h7v2bsja82s6yb-vulnix-1.8.2/lib/python3.7/site-packages/vulnix/main.py", line 138, in main
    nvd.update()
  File "/nix/store/4zyb0g5h6vfnxrzhl6h7v2bsja82s6yb-vulnix-1.8.2/lib/python3.7/site-packages/vulnix/nvd.py", line 99, in update
    self.has_updates |= archive.update(self.mirror)
  File "/nix/store/4zyb0g5h6vfnxrzhl6h7v2bsja82s6yb-vulnix-1.8.2/lib/python3.7/site-packages/vulnix/nvd.py", line 193, in update
    with Download(mirror + self.upstream_filename) as xml:
  File "/nix/store/4zyb0g5h6vfnxrzhl6h7v2bsja82s6yb-vulnix-1.8.2/lib/python3.7/site-packages/vulnix/nvd.py", line 142, in __enter__
    self.xml = decompress(r.raw)
  File "/nix/store/4zyb0g5h6vfnxrzhl6h7v2bsja82s6yb-vulnix-1.8.2/lib/python3.7/site-packages/vulnix/nvd.py", line 122, in decompress
    shutil.copyfileobj(f_in, tf)
  File "/nix/store/4c3z5r6yxsf2cxwwyazhdn92xixn4j5b-python3-3.7.5/lib/python3.7/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/nix/store/4c3z5r6yxsf2cxwwyazhdn92xixn4j5b-python3-3.7.5/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/nix/store/4c3z5r6yxsf2cxwwyazhdn92xixn4j5b-python3-3.7.5/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/nix/store/4c3z5r6yxsf2cxwwyazhdn92xixn4j5b-python3-3.7.5/lib/python3.7/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/nix/store/4c3z5r6yxsf2cxwwyazhdn92xixn4j5b-python3-3.7.5/lib/python3.7/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'<!')
```
vulnix 1.8.2

**Comment by ckauhaus** [comment]
Interesting. What is your full command line? Just `vulnix` or did you provide any options?

**Comment by dR3b** [comment]
OK:
```
vulnix
```
Not OK:
```
vulnix --system
vulnix -R /nix/store/*.drv
```
The version in NixOS seems to be very old (vulnix 1.8.2).

**Comment by ckauhaus** [comment]
This version of vulnix tries to get the old XML feed. NIST discontinued the XML feed and provides now only the JSON feed. Use vulnix 1.9.2+ from current master which has been fixed. Sorry for the annoyance.

Dup #55

**Comment by dR3b** [comment]
Why no backport for 19.09?

**Comment by ckauhaus** [comment]
Sounds like a good idea. I'll do that after getting 1.9.3 out.

**Comment by ckauhaus** [comment]
Well... 19.03 is EOL. Trying to get the latest version at least into 20.03.
