### ISSUE TITLE
nix show-derivation finds derivers nix-store -qd doesn't

### ISSUE THREAD

**Issue by chkno** [flyingcircusio/vulnix#69]
The problem:

    $ nix-build '<nixpkgs>' -A speex
    /nix/store/6w7f9hkizdid4kcnicdv3scq5b2s3qky-speex-1.2.0
    $ vulnix $(!!)
    error: path '/nix/store/ysmdckcl3acmkbf1wpv5fdkc8q1zcl2m-speex-1.2.0.drv' is not valid
    Traceback (most recent call last):
      File "/nix/store/i8v78fkandiw7524klzgq9ngipk4mk3v-vulnix-1.9.6/bin/.vulnix-wrapped", line 9, in <module>
        sys.exit(main())
      File "/nix/store/c75zihvc0hdkm93bkl8vb7v1p540wx21-python3.7-click-7.1.2/lib/python3.7/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/nix/store/c75zihvc0hdkm93bkl8vb7v1p540wx21-python3.7-click-7.1.2/lib/python3.7/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/nix/store/c75zihvc0hdkm93bkl8vb7v1p540wx21-python3.7-click-7.1.2/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/nix/store/c75zihvc0hdkm93bkl8vb7v1p540wx21-python3.7-click-7.1.2/lib/python3.7/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/nix/store/i8v78fkandiw7524klzgq9ngipk4mk3v-vulnix-1.9.6/lib/python3.7/site-packages/vulnix/main.py", line 139, in main
        store = populate_store(gc_roots, paths, requisites)
      File "/nix/store/i8v78fkandiw7524klzgq9ngipk4mk3v-vulnix-1.9.6/lib/python3.7/site-packages/vulnix/main.py", line 59, in populate_store
        store.add_path(path)
      File "/nix/store/i8v78fkandiw7524klzgq9ngipk4mk3v-vulnix-1.9.6/lib/python3.7/site-packages/vulnix/nix.py", line 40, in add_path
        for candidate in call(['nix-store', '-qR', deriver]).splitlines():
      File "/nix/store/i8v78fkandiw7524klzgq9ngipk4mk3v-vulnix-1.9.6/lib/python3.7/site-packages/vulnix/utils.py", line 15, in call
        output = subprocess.check_output(cmd, stderr=capture)
      File "/nix/store/dgjm8090l365id2m7zhi6l7864kkb3n7-python3-3.7.10/lib/python3.7/subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "/nix/store/dgjm8090l365id2m7zhi6l7864kkb3n7-python3-3.7.10/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['nix-store', '-qR', '/nix/store/ysmdckcl3acmkbf1wpv5fdkc8q1zcl2m-speex-1.2.0.drv']' returned non-zero exit status 1.

vulnix uses `nix-store -qd` to find the deriver for nix store paths.  Sometimes this doesn't work:

    $ nix-build '<nixpkgs>' -A speex
    /nix/store/6w7f9hkizdid4kcnicdv3scq5b2s3qky-speex-1.2.0
    $ nix-store -qd $(!!)
    /nix/store/ysmdckcl3acmkbf1wpv5fdkc8q1zcl2m-speex-1.2.0.drv
    $ ls $(!!)
    ls: cannot access '/nix/store/ysmdckcl3acmkbf1wpv5fdkc8q1zcl2m-speex-1.2.0.drv': No such file or directory

But `nix show-derivation` produces the correct deriver path:

    $ nix-build '<nixpkgs>' -A speex
    /nix/store/6w7f9hkizdid4kcnicdv3scq5b2s3qky-speex-1.2.0
    $ nix --experimental-features nix-command show-derivation $(!!) | jq -r 'keys[]'
    /nix/store/83fps98i41vba4yj20vjycqhgnxhy4v6-speex-1.2.0.drv
    $ ls $(!!)
    /nix/store/83fps98i41vba4yj20vjycqhgnxhy4v6-speex-1.2.0.drv

Internally, `nix-store -qd` uses `QueryPathInfo` to find the bad deriver path, which does this SQL query:

    $ cp /nix/var/nix/db/db.sqlite /tmp/nix-store-db.sqlite
    $ sqlite3 -readonly /tmp/nix-store-db.sqlite
    sqlite> select deriver from ValidPaths where path = '/nix/store/6w7f9hkizdid4kcnicdv3scq5b2s3qky-speex-1.2.0';
    /nix/store/ysmdckcl3acmkbf1wpv5fdkc8q1zcl2m-speex-1.2.0.drv

Correspondingly, `nix show-derivation` internally uses `QueryValidDerivers` to find the good deriver path, which does this SQL query:

    sqlite> select v.path from DerivationOutputs d join ValidPaths v on d.drv = v.id where d.path = '/nix/store/6w7f9hkizdid4kcnicdv3scq5b2s3qky-speex-1.2.0';
    /nix/store/83fps98i41vba4yj20vjycqhgnxhy4v6-speex-1.2.0.drv

I don't know where the bad .drv paths come from.  I guess vulnix should just check `nix show-derivation` if `nix-store -qd` gives a non-existent path?

---

These problematic paths are common in `nix-store --gc --print-roots` output (which powers `--memory`).  Shell script to print out all the discrepancies:

    exists() { if [[ -e "$1" ]];then echo "$1 (exists)"; else echo  "$1 (DOES NOT EXIST)";fi; }
    nix-store --gc --print-roots |
      while read src arrow path;do
        old=$(nix-store -qd "$path")
        new=$(nix --experimental-features nix-command show-derivation "$path" | jq -r 'keys[]')
        if [[ "$old" != "$new" ]];then
          echo "$path: nix-store says $(exists "$old") but nix show-derivation says $(exists "$new")"
        fi
      done

On my NixOS machine, this emits 85 derivations with discrepancies.  The speex example shows as:

    /nix/store/6w7f9hkizdid4kcnicdv3scq5b2s3qky-speex-1.2.0: nix-store says /nix/store/ysmdckcl3acmkbf1wpv5fdkc8q1zcl2m-speex-1.2.0.drv (DOES NOT EXIST) but nix show-derivation says /nix/store/83fps98i41vba4yj20vjycqhgnxhy4v6-speex-1.2.0.drv (exists)

**Comment by ckauhaus** [comment]
Good catch :-)
